Raspberrypi/hiverize/webinterface/views/network.py
import NetworkManager
import subprocess
import re
import uuid
import ipaddress
from flask import Blueprint, render_template, request, redirect, url_for

network = Blueprint('network', __name__)

nm = NetworkManager.NetworkManager
nm_settings = NetworkManager.Settings
wlan0 = nm.GetDeviceByIpIface('wlan0')
eth0 = nm.GetDeviceByIpIface('eth0')
nm_connections = {}

def getConnectionByName(name):
    global nm_settings
    for connection in nm_settings.ListConnections():
        settings = connection.GetSettings()
        connection_id = settings['connection']['id']
        connection_uuid = settings['connection']['uuid']
        if connection_id == name:
            return connection
    return None


def wifi_scan():
    # Create a listwith all visible SSIDS
    # A bit hacky, but NetworkManager won't scan while in AP mode
    res = subprocess.check_output('sudo iw dev wlan0 scan', 
                                   shell=True)
    ap_in_res = re.split('BSS [0-9a-f:]{17}.*\n', res.decode('utf-8'))
    ap_list = []

    re_ssid = re.compile('SSID: (.+)\n')
    for ap in ap_in_res[1:]:
        ssid = re.search(re_ssid, ap).group(1)
        if re.search('\tcapability:.*Privacy.*\n', ap) is not None:
            encryption = True
            if re.search('\t(RSN|WPA):', ap) is not None:
                key_mgmt = 'wpa-psk'
            else:
                key_mgmt = 'none'
        else:
            encryption = False
            key_mgmt = None
        ap_list.append({'ssid': ssid, 
                        'encryption': encryption, 
                        'key-mgmt': key_mgmt})
    
    return ap_list

def is_server_reachable(url):
    try:
        subprocess.check_call(["ping", "-c", "1", url])
    except subprocess.CalledProcessError:
        return False
    else:
        return True

@network.route('/')
def index():
    # Check if an internet connection is available 
    # and if the hiverize server can be reached
    hiverize_server_reachable = is_server_reachable(
            'bhive.informatik.uni-bremen.de')
    if not hiverize_server_reachable:
        cloudflare_reachable = is_server_reachable('1.1.1.1')
    else:
        cloudflare_reachable = True
    
    print(hiverize_server_reachable)

    eth0_connected = (eth0.State==100)
    if eth0_connected:
        eth0_ipv4 = eth0.Ip4Config.AddressData
    else: 
        eth0_ipv4 = None
        
    wlan0_connected = (wlan0.State==100)
    wlan0_ap = (wlan0.Mode==3)
    if wlan0_connected:
        wlan0_ipv4 = wlan0.Ip4Config.AddressData
    else:
        wlan0_ipv4 = None
    
    return render_template('network/index.html', 
                           hiverize_server_reachable=hiverize_server_reachable,
                           cloudflare_reachable=cloudflare_reachable,
                           eth0_connected=eth0_connected,
                           eth0_ipv4=eth0_ipv4,
                           wlan0_ap=wlan0_ap,
                           wlan0_connected=wlan0_connected,
                           wlan0_ipv4=wlan0_ipv4
                           ) 
    
@network.route('/lan', methods=['GET', 'POST'])
def lan_setup():
    return render_template('network/setup.html',
                           interface_name='eth0',
                           id='wired')

    
@network.route('/wifi', methods=['GET', 'POST'])
def wifi_setup():
    ap_list = wifi_scan()
    if request.method == 'GET':
        # Check if internet is available (maybe a cable is connected)
        network_state = nm.CheckConnectivity()
        
        return render_template('network/ap_list.html', 
                               title='SSID wählen', 
                               network_state=network_state,
                               ap_list=ap_list)
    else:
        if request.form['hidden_ssid']:
            ap_info = {'ssid': request.form['hidden_ssid'],
                       'encryption': True,
                       'key-mgmt': 'wpa-psk'}

        else:
            ssid = request.form['ssid']
            for ap in ap_list:
                if ap['ssid'] == ssid:
                    ap_info = ap
                    break

        return render_template('network/setup.html',
                               interface_name='wlan0',
                               id='wifi',
                               ap_info=ap_info)
    
@network.route('/save', methods=['POST'])
def save():
    connection = getConnectionByName(request.form['id'])
    if connection is not None:
        connection.Delete()

    network_settings = {'connection': {}}
    network_settings['connection']['uuid'] = str(uuid.uuid1())
    network_settings['connection']['id'] = request.form['id']
    network_settings['connection']['autoconnect'] = True
    network_settings['connection']['autoconnect-priority'] = 1
    interface_name = request.form['interface-name']
    network_settings['connection']['interface-name'] = interface_name
    if interface_name == 'wlan0':
        network_settings['connection']['type'] = '802-11-wireless'
        network_settings['802-11-wireless'] = {'ssid': request.form['ssid']}

        if request.form['encryption']:
            network_settings['802-11-wireless-security'] = {
                'key-mgmt': request.form['key-mgmt'],
                'psk': request.form['psk']
            }
        
    elif interface_name == 'eth0':
        network_settings['connection']['type'] = '802-3-ethernet'

    network_settings['ipv4'] = {'method': request.form['ipv4_method']}
    if request.form['ipv4_method'] == 'manual':
        network_settings['ipv4']['address-data'] = [{
                'address': request.form['address'],
                'prefix': request.form['prefix']}]
        network_settings['ipv4']['gateway'] = request.form['gateway']
        network_settings['ipv4']['dns'] = [ request.form['dns'] ]

    connection = nm_settings.AddConnection(network_settings)
    if interface_name == 'wlan0':    
        nm.ActivateConnection(connection, wlan0, '/')
    else:
        nm.ActivateConnection(connection, eth0, '/')

    return redirect( url_for('network.index') )

Raspberrypi/hiverize/webinterface/templates/network/ap_list.html
{% extends 'base.html' %}

{% block content %}

<form action="{{ url_for('network.wifi_setup') }}" method="post">
	{% for ap in ap_list %}
	<input type="radio" name="ssid" value="{{ ap.ssid }}"> {{ ap.ssid }} <br>
	{% endfor %}
	<br>
	If SSID is not in the list enter the name in the following field:<br>
	<input type="text" name="hidden_ssid">
	<br>
	<input type="submit" value="WLan einrichten">
</form>

{% endblock %}

Raspberrypi/hiverize/webinterface/templates/network/index.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Übersicht{% endblock %}</h1>
{% endblock %}

{% block content %}
	{% if hiverize_server_reachable and cloudflare_reachable %}
		<div id="success">
			Es ist eine Internetverbindung verfügbar. Das Einrichten des Netzwerks kann übersprungen werden.		
		</div>
	{% elif cloudflare_reachable %}
		<div id="warning">
			Es ist eine Internetverbindung verfügbar, der Hiverize-Server ist jedoch nicht erreichbar. Das Einrichten des Netzwerks kann übersprungen werden.		
		</div>
	{% else %}
		<div id="error">
			Es ist keine Internetverbindung verfügbar. Bitte eine Netzwerkverbindung einrichten.<br>
			Ohne Interverbindung ist nur eine lokale Aufzeichnung der Daten möglich		
		</div>
	{% endif %}
	
	<div>
		<b>LAN-Kabel:
    	{% if eth0_connected %}
    		verbunden</b><br>
    		IP-Adresse: 
    		{% for ipv4 in eth0_ipv4 %}
    			{{ ipv4.address }}/{{ ipv4.prefix }}
    		{% endfor %}
    	{% else %}
    		nicht verbunden</b>
    	{% endif %}
    	<a href="{{ url_for('network.lan_setup') }}" >LAN einrichten</a>
    </div>
    
    <div>
		<b>WLan:
		{% if wlan0_connected %}
    		{% if wlan0_ap %}
    			Access Point</b>
    		{% else %}
    			verbunden</b>
    		{% endif %}
    		<br>
    		IP-Adresse: 
    		{% for ipv4 in wlan0_ipv4 %}
    			{{ ipv4.address }}/{{ ipv4.prefix }}
    		{% endfor %}
    	{% else %}
    		nicht verbunden</b>
    	{% endif %}
    	<a href="{{ url_for('network.wifi_setup') }}" >WLan einrichten</a>
	</div>
	<br>
{% endblock %}

Raspberrypi/hiverize/webinterface/templates/network/setup.html
{% extends 'base.html' %}

{% block content %}
<form action="{{ url_for('network.save') }}" method="post">

	<p>
		<label for="interface_name">Interface:</label>
		<input type="text" name="interface-name" value="{{ interface_name }}" readonly> 	
	</p>
	<p>
		<label for="name">Name</label>
		<input type="text" name="id" value="{{ id }}" readonly>
	</p>
	{% if interface_name=='wlan0' %}
		<h3>WLan-Einstellungen</h3>
		<p>
			<label for="ssid">SSID:</label>
			<input type="text" name="ssid" value="{{ ap_info['ssid'] }}" readonly>
		</p>
		<p>
			<label for="encryption">Verschlüsselt:</label>
			<input type="checkbox" name="encryption"  {{ 'checked' if ap_info['encryption'] else '' }}>
		</p>
		{% if ap_info['encryption'] %}
			<p>
				<label for="encryption">Schlüsselaustausch:</label>
				<input type="text" name="key-mgmt" value="{{ ap_info['key-mgmt'] }}" readonly>
			</p>
			<p>
				<label for="psk">Passwort:</label>
				<input type="text" name="psk">
			</p>
		{% endif %}
	{% endif %}
	<h3>IPv4 Adresse</h3>
	<p>
		<input type="radio" name="ipv4_method" value="auto" onclick="ipv4_box(false)" checked> DHCP
		<input type="radio" name="ipv4_method" value="manual" onclick="ipv4_box(true)"> Statisch
	</p>
	<p class="ipv4_static">
		<label for="address">Adresse:</label>
		<input type="text" name="address">
	</p>
	<p class="ipv4_static">
		<label for="prefix">Prefix:</label>
		<input type="number" name="prefix" value="24">
	</p>
	<p class="ipv4_static">
		<label for="gateway">Gateway:</label>
		<input type="text" name="gateway">
	</p>
	<p class="ipv4_static">
		<label for="dns">DNS Server:</label>
		<input type="text" name="dns" value="1.1.1.1">
	</p>
	<input type="submit" value="Einrichten">
</form>

<script>
	function ipv4_box(visible) {
		var elements = document.getElementsByClassName("ipv4_static");
		for (var idx=0; idx<elements.length; idx++) {
			var item = elements[idx];
			if (visible) {
				item.style.display = 'block';
			}
			else {
				item.style.display = 'none';
			}
		}
	}
</script>
{% endblock %}